### ISSUE TITLE
soma.summary.txt - filterStatus

### ISSUE THREAD

**Issue by TalRichter** [weng-lab/TEMP2#5]
Hi,
I would like to know how the filterStatus in the soma.summary file is calculated.
Thank you
Tal

**Comment by tianxiongbb** [comment]
"Short" is for those transposons shorter than 500bp, which lack the ability to distinguish end and center regions to estimate somatic insertion rate.
"Imbalance" is for those transposons whose somatic insertion supporting reads mainly align to one end of them (more than 8 folders than another end). "Imbalanced" transposons should be processed with care, their high somatic insertion rates are generally introduced by alignment bias due to assembly quality or other reasons.

**Comment by tianxiongbb** [comment]
> Hi, I would like to know how the filterStatus in the soma.summary file is calculated. Thank you Tal

"Short" is for those transposons shorter than 500bp, which lack the ability to distinguish end and center regions to estimate somatic insertion rate.
"Imbalance" is for those transposons whose somatic insertion supporting reads mainly align to one end of them (more than 8 folders than another end). "Imbalanced" transposons should be processed with care, their high somatic insertion rates are generally introduced by alignment bias due to assembly quality or other reasons.
